### GET to http://localhost:3003/api/blogs
GET http://localhost:3003/api/blogs

### POST to http://localhost:3003/api/blogs
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "title String 2",
  "author": "author String 2",
  "url": "url String 2",
  "likes": 232
}